### ISSUE TITLE
Add Navbar

### ISSUE THREAD

**Issue by shivshankar9** [iiitv/hacktoberfest21-web-gdsc-iiitv#70]
I wanted to contribute for hacktoberfest please assign me

**Comment by Rajat760** [comment]
please see #73

**Comment by shivshankar9** [comment]
> please see #73

Don't try to be oversmart
For your kind information I have created issue first,
You just copied my issue,
In open source you need to first create issue by self or check others issues which not solved , and for every contribution you need to atleast ask admin
Please go through contribution guidelines.

**Comment by AnshuPathak-88825** [comment]
pls assign me this issue

**Comment by shivshankar9** [comment]
> @shivshankar9 pls assign me this issue

I'm not admin bro, also you should not waste time in this project go for other project here project admin so busy they don't even merged single PR from me 😁
